package project66;

import javax.swing.JOptionPane;

public class CurrencyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyJFrame1
     */
    public CurrencyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency");
        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Select output currency : ");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Enter amount : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THB", "USD", "EUR", "GBP", "JPY", "KRW" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setText("0.00");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THB", "USD", "EUR", "GBP", "JPY", "KRW" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField2.setText("0.00");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Select input currency : ");

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency Converter");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Converted value :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jComboBox1, 0, 92, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            double value = Double.parseDouble(jTextField1.getText());
            switch (jComboBox1.getSelectedIndex()) {
                case 0 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(value));
                        case 1 -> jTextField2.setText(String.valueOf(String.format("%.2f", thbToUsd(value))));
                        case 2 -> jTextField2.setText(String.valueOf(String.format("%.2f", thbToEur(value))));
                        case 3 -> jTextField2.setText(String.valueOf(String.format("%.2f", thbToGbp(value))));
                        case 4 -> jTextField2.setText(String.valueOf(String.format("%.2f", thbToJpy(value))));
                        default -> jTextField2.setText(String.valueOf(String.format("%.2f", thbToKrw(value))));
                    }
                }
                case 1 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(String.format("%.2f", usdToThb(value))));
                        case 1 -> jTextField2.setText(String.valueOf(value));
                        case 2 -> jTextField2.setText(String.valueOf(String.format("%.2f", usdToEur(value))));
                        case 3 -> jTextField2.setText(String.valueOf(String.format("%.2f", usdToGbp(value))));
                        case 4 -> jTextField2.setText(String.valueOf(String.format("%.2f", usdToJpy(value))));
                        default -> jTextField2.setText(String.valueOf(String.format("%.2f", usdToKrw(value))));
                    }
                }
                case 2 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(String.format("%.2f", eurToThb(value))));
                        case 1 -> jTextField2.setText(String.valueOf(String.format("%.2f", eurToUsd(value))));
                        case 2 -> jTextField2.setText(String.valueOf(value));
                        case 3 -> jTextField2.setText(String.valueOf(String.format("%.2f", eurToGbp(value))));
                        case 4 -> jTextField2.setText(String.valueOf(String.format("%.2f", eurToJpy(value))));
                        default -> jTextField2.setText(String.valueOf(String.format("%.2f", eurToKrw(value))));
                    }
                }
                case 3 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(String.format("%.2f", gbpToThb(value))));
                        case 1 -> jTextField2.setText(String.valueOf(String.format("%.2f", gbpToUsd(value))));
                        case 2 -> jTextField2.setText(String.valueOf(String.format("%.2f", gbpToEur(value))));
                        case 3 -> jTextField2.setText(String.valueOf(value));
                        case 4 -> jTextField2.setText(String.valueOf(String.format("%.2f", gbpToJpy(value))));
                        default -> jTextField2.setText(String.valueOf(String.format("%.2f", gbpToKrw(value))));
                    }
                }
                case 4 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(String.format("%.2f", jpyToThb(value))));
                        case 1 -> jTextField2.setText(String.valueOf(String.format("%.2f", jpyToUsd(value))));
                        case 2 -> jTextField2.setText(String.valueOf(String.format("%.2f", jpyToEur(value))));
                        case 3 -> jTextField2.setText(String.valueOf(String.format("%.2f", jpyToGbp(value))));
                        case 4 -> jTextField2.setText(String.valueOf(value));
                        default -> jTextField2.setText(String.valueOf(String.format("%.2f", jpyToKrw(value))));
                    }
                }
                default -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(String.format("%.2f", krwToThb(value))));
                        case 1 -> jTextField2.setText(String.valueOf(String.format("%.2f", krwToUsd(value))));
                        case 2 -> jTextField2.setText(String.valueOf(String.format("%.2f", krwToEur(value))));
                        case 3 -> jTextField2.setText(String.valueOf(String.format("%.2f", krwToGbp(value))));
                        case 4 -> jTextField2.setText(String.valueOf(String.format("%.2f", krwToJpy(value))));
                        default -> jTextField2.setText(String.valueOf(value));
                    }
                }

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid value!!!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("0.00");
        jTextField2.setText("0.00");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainMenuJFrame menuJFrame = new MainMenuJFrame();
        menuJFrame.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public double thbToUsd(double value){
        return value*0.028;
    }
    public double thbToEur(double value){
        return value*0.026;
    }
    public double thbToGbp(double value){
        return value*0.023;
    }
    public double thbToJpy(double value){
        return value*4.14;
    }
    public double thbToKrw(double value){
        return value*37.55;
    }
    
    public double usdToThb(double value){
        return value*36.12;
    }
    public double usdToEur(double value){
        return value*0.95;
    }
    public double usdToGbp(double value){
        return value*0.82;
    }
    public double usdToJpy(double value){
        return value*149.65;
    }
    public double usdToKrw(double value){
        return value*1356.22;
    }
    
    public double eurToThb(double value){
        return value*38.12;
    }
    public double eurToUsd(double value){
        return value/0.95;
    }
    public double eurToGbp(double value){
        return value*0.87;
    }
    public double eurToJpy(double value){
        return value*158.33;
    }
    public double eurToKrw(double value){
        return value*1434.81;
    }
    
    public double gbpToThb(double value){
        return value*43.81;
    }
    public double gbpToUsd(double value){
        return value*1.21;
    }
    public double gbpToEur(double value){
        return value*1.15;
    }
    public double gbpToJpy(double value){
        return value*181.86;
    }
    public double gbpToKrw(double value){
        return value*1644.82;
    }
    
    public double jpyToThb(double value){
        return value*0.24;
    }
    public double jpyToUsd(double value){
        return value/149.65;
    }
    public double jpyToEur(double value){
        return value/158.33;
    }
    public double jpyToGbp(double value){
        return value/181.86;
    }
    public double jpyToKrw(double value){
        return value*9.06;
    }
    
    public double krwToThb(double value){
        return value*0.027;
    }
    public double krwToUsd(double value){
        return value/1356.22;
    }
    public double krwToEur(double value){
        return value/1434.81;
    }
    public double krwToGbp(double value){
        return value/1644.82;
    }
    public double krwToJpy(double value){
        return value/9.06;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
