package project66;

import javax.swing.JOptionPane;

/**
 *
 * @author Jay
 */
public class LengthJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LengthJFrame1
     */
    public LengthJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Length Converter");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        backButton1.setText("BMI");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Converted value :");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Select output unit : ");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Enter amount : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeters(cm)", "Meters(m)", "Kilometers(km)", "Miles(mi)", "Inches(in)", "Feet(ft)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setText("0.00");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimeters(cm)", "Meters(m)", "Kilometers(km)", "Miles(mi)", "Inches(in)", "Feet(ft)" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField2.setText("0.00");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Select input unit : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2))
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(backButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            double value = Double.parseDouble(jTextField1.getText());
            switch (jComboBox1.getSelectedIndex()) {
                case 0 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(value));
                        case 1 -> jTextField2.setText(String.valueOf(cmToM(value)));
                        case 2 -> jTextField2.setText(String.valueOf(cmToKm(value)));
                        case 3 -> jTextField2.setText(String.valueOf(cmToMi(value)));
                        case 4 -> jTextField2.setText(String.valueOf(cmToIn(value)));
                        default -> jTextField2.setText(String.valueOf(cmToFt(value)));
                    }
                }
                case 1 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(mToCm(value)));
                        case 1 -> jTextField2.setText(String.valueOf(value));
                        case 2 -> jTextField2.setText(String.valueOf(mToKm(value)));
                        case 3 -> jTextField2.setText(String.valueOf(mToMi(value)));
                        case 4 -> jTextField2.setText(String.valueOf(mToIn(value)));
                        default -> jTextField2.setText(String.valueOf(mToFt(value)));
                    }
                }
                case 2 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(kmToCm(value)));
                        case 1 -> jTextField2.setText(String.valueOf(kmToM(value)));
                        case 2 -> jTextField2.setText(String.valueOf(value));
                        case 3 -> jTextField2.setText(String.valueOf(kmToMi(value)));
                        case 4 -> jTextField2.setText(String.valueOf(kmToIn(value)));
                        default -> jTextField2.setText(String.valueOf(kmToFt(value)));
                    }
                }
                case 3 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(miToCm(value)));
                        case 1 -> jTextField2.setText(String.valueOf(miToM(value)));
                        case 2 -> jTextField2.setText(String.valueOf(miToKm(value)));
                        case 3 -> jTextField2.setText(String.valueOf(value));
                        case 4 -> jTextField2.setText(String.valueOf(miToIn(value)));
                        default -> jTextField2.setText(String.valueOf(miToFt(value)));
                    }
                }
                case 4 -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(inToCm(value)));
                        case 1 -> jTextField2.setText(String.valueOf(inToM(value)));
                        case 2 -> jTextField2.setText(String.valueOf(inToKm(value)));
                        case 3 -> jTextField2.setText(String.valueOf(inToMi(value)));
                        case 4 -> jTextField2.setText(String.valueOf(value));
                        default -> jTextField2.setText(String.valueOf(inToFt(value)));
                    }
                }
                default -> {
                    switch (jComboBox2.getSelectedIndex()) {
                        case 0 -> jTextField2.setText(String.valueOf(ftToCm(value)));
                        case 1 -> jTextField2.setText(String.valueOf(ftToM(value)));
                        case 2 -> jTextField2.setText(String.valueOf(ftToKm(value)));
                        case 3 -> jTextField2.setText(String.valueOf(ftToMi(value)));
                        case 4 -> jTextField2.setText(String.valueOf(ftToIn(value)));
                        default -> jTextField2.setText(String.valueOf(value));
                    }
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid value!!!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("0.00");
        jTextField2.setText("0.00");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainMenuJFrame menuJFrame = new MainMenuJFrame();
        menuJFrame.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        BmiJFrame bmiJFrame = new BmiJFrame();
        bmiJFrame.show();
        dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    public double cmToM(double value){
        return value/100;
    }
    public double cmToKm(double value){
        return value/100000;
    }
    public double cmToMi(double value){
        return value*6.21371192/100;
    }
    public double cmToIn(double value){
        return value*0.393700787;
    }
    public double cmToFt(double value){
        return value*0.032808399;
    }
    
    public double mToCm(double value){
        return value*100;
    }
    public double mToKm(double value){
        return value/1000;
    }
    public double mToMi(double value){
        return value*0.000621371192;
    }
    public double mToIn(double value){
        return value*39.3700787;
    }
    public double mToFt(double value){
        return value*3.2808;
    }
    
    public double kmToCm(double value){
        return value*100000;
    }
    public double kmToM(double value){
        return value*1000;
    }
    public double kmToMi(double value){
        return value*0.621371192;
    }
    public double kmToIn(double value){
        return value*39370.0787;
    }
    public double kmToFt(double value){
        return value*3280.8399;
    }
    
    public double miToCm(double value){
        return value*160934.4;
    }
    public double miToM(double value){
        return value*1609.344;
    }
    public double miToKm(double value){
        return value*1.609344;
    }
    public double miToIn(double value){
        return value*63360;
    }
    public double miToFt(double value){
        return value*5280;
    }
    
    public double inToCm(double value){
        return value*2.54;
    }
    public double inToM(double value){
        return value*0.0254;
    }
    public double inToKm(double value){
        return value*2.54*Math.pow(10, -5);
    }
    public double inToMi(double value){
        return value*1.57828283*Math.pow(10, -5);
    }
    public double inToFt(double value){
        return value*0.0833333333;
    }
    
    public double ftToCm(double value){
        return value*30.48;
    }
    public double ftToM(double value){
        return value*0.3048;
    }
    public double ftToKm(double value){
        return value*0.0003048;
    }
    public double ftToMi(double value){
        return value*0.000189393939;
    }
    public double ftToIn(double value){
        return value*12;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LengthJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LengthJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LengthJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LengthJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LengthJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
